version: "3.8"

services:
    
    node:
        image: node:lts-alpine
        container_name: aluguel_node
        volumes:
            - ./:/var/www/app
        working_dir: /var/www/app
        command: >
            sh -c "npm install
            && npm run dev"
        ports:
            - "8000:5173"
        networks:
            - dev

networks:
    dev:
        driver: bridge
        
